#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
[ -z "$OTB_TRACKER_INTERFACE_LATENCY" ] && exit 0
logger -t "otb-tracker_log_latency" "$OTB_TRACKER_METHOD $OTB_TRACKER_INTERFACE in $OTB_TRACKER_INTERFACE_LATENCY ms on $OTB_TRACKER_HOST"
