#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
[ -z "$OTB_TRACKER_INTERFACE_PUBLIC_IP" ] && exit 0
logger -t "otb-tracker_log_pub_ip" "$OTB_TRACKER_METHOD $OTB_TRACKER_INTERFACE public ip : $OTB_TRACKER_INTERFACE_PUBLIC_IP"
