#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
START=90
STOP=10

USE_PROCD=1

validate() {
	section="$1"
	tracking_method="$2"
	shift
	shift
	uci_validate_section otb-tracker "$tracking_method" "$section" \
		'host:host' \
		'interface:string' \
		'timeout:uinteger:2' \
		'options:string' \
		"$@"
}

start_track_icmp() {
	validate "$1" "$2"
	procd_open_instance
	procd_set_param command /bin/otb-tracker_"$2" -t "$timeout" -h "$host" -i "$interface" "$options"
	procd_set_param respawn  0 5 0
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

start_track_tcp_curl() {
	validate "$1" "$2"
	procd_open_instance
	procd_set_param command /bin/otb-tracker_"$2" -t "$timeout" -h "$host" -i "$interface" "$options"
	procd_set_param respawn  0 5 0
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

start_track_dns() {
	validate "$1" "$2" 'domain:host'
	procd_open_instance
	procd_set_param command /bin/otb-tracker_"$2" -t "$timeout" -h "$host" -i "$interface" -d "$domain" "$options"
	procd_set_param respawn  0 5 0
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

start_service() {
	config_load otb-tracker
	for tracker in /bin/otb-tracker_*; do
		tracking_method=${tracker#/bin/otb-tracker_}
		echo "$tracking_method"
		config_foreach start_track_"$tracking_method" "$tracking_method" "$tracking_method"
	done
}
