#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

otb_tracker_export_vars() {
	export OTB_TRACKER_INTERFACE
	export OTB_TRACKER_METHOD
	export OTB_TRACKER_TIMEOUT
	export OTB_TRACKER_HOST
	export OTB_TRACKER_DOMAIN
	export OTB_TRACKER_STATUS
	export OTB_TRACKER_INTERFACE_STATE
	export OTB_TRACKER_INTERFACE_PUBLIC_IP
	export OTB_TRACKER_INTERFACE_LATENCY
}

otb_tracker_post_tracking() {
	for file_path in /usr/share/otb/tracking.d/*; do
		[ -f "$file_path" ] || continue
		"$file_path"
	done
}

otb_tracker_check_args() {
	for option in "$@"; do
		[ -z "$option" ] && usage
	done
}

otb_tracker_set_status() {
	[ "$1" = 0 ] && OTB_TRACKER_STATUS="OK" || OTB_TRACKER_STATUS="ERROR"
}

otb_tracker_retrieve_args() {
	while [ "$1" != "" ]; do
		case $1 in
			-i)	shift
				OTB_TRACKER_INTERFACE="$1";;
			-h) shift
				OTB_TRACKER_HOST="$1";;
			-t) shift
				OTB_TRACKER_TIMEOUT="$1";;
			-d)	shift
				OTB_TRACKER_DOMAIN="$1";;
			*)	OTB_TRACKER_OPTIONS="$OTB_TRACKER_OPTIONS $1"
		esac
		shift
	done
}

otb_tracker_init_tracking() {
	otb_tracker_retrieve_args "$@"
	otb_tracker_check_args $(needed_args)
	otb_tracker_export_vars
}
