#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/otb-tracker

tracking_command() {
	curl \
		--interface "$OTB_TRACKER_INTERFACE" \
		--max-time "$OTB_TRACKER_TIMEOUT" \
		--silent \
		$OTB_TRACKER_OPTIONS \
		"$OTB_TRACKER_HOST"
}

tracking_result() {
	[ "$OTB_TRACKER_STATUS" = "OK" ] && OTB_TRACKER_INTERFACE_PUBLIC_IP="$OTB_TRACKER_RESULT"
}

OTB_TRACKER_METHOD='tcp_curl'
otb_tracker_track "$@"
