#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/otb-tracker

usage() {
	printf "Usage : %s: [-t TIMEOUT] [-h HOST] [-i INTERFACE]\n" "$0"
	exit 1
}

needed_args() {
	echo OTB_TRACKER_TIMEOUT OTB_TRACKER_HOST OTB_TRACKER_INTERFACE OTB_TRACKER_RETRY
}

tracking_command() {
	ping \
		-c 1 \
		-I "$OTB_TRACKER_INTERFACE" \
		-W "$OTB_TRACKER_TIMEOUT" \
		$OTB_TRACKER_OPTIONS \
		"$OTB_TRACKER_HOST" 2>&1
}

tracking_result() {
	[ "$OTB_TRACKER_STATUS" = "OK" ] && OTB_TRACKER_INTERFACE_LATENCY=$( echo "$OTB_TRACKER_RESULT" | cut -d '/' -s -f4 )
}

OTB_TRACKER_METHOD='icmp'
otb_tracker_track "$@"
