#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/otb-tracker
. /lib/functions/network.sh

_get_interface_ip() {
	network_flush_cache
	network_get_ipaddr interface_ip "$OTB_TRACKER_INTERFACE"
}

tracking_command() {
	_get_interface_ip
	dig "$OTB_TRACKER_DOMAIN" @"$OTB_TRACKER_HOST" -b "$interface_ip" +time="$OTB_TRACKER_TIMEOUT" +short $OTB_TRACKER_OPTIONS
}

tracking_result() {
	[ "$OTB_TRACKER_STATUS" = "OK" ] && OTB_TRACKER_INTERFACE_PUBLIC_IP="$OTB_TRACKER_RESULT"
}

OTB_TRACKER_METHOD='dns'
otb_tracker_track "$@"
