#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/otb-tracker
. /lib/functions/network.sh

usage() {
	printf "Usage : %s: [-t TIMEOUT] [-h HOST] [-i INTERFACE]\n" "$0"
	exit 1
}

needed_args() {
	echo "$OTB_TRACKER_TIMEOUT" "$OTB_TRACKER_HOST" "$OTB_TRACKER_INTERFACE"
}

_get_interface_ip() {
	network_flush_cache
	network_get_ipaddrs interface_ip "$OTB_TRACKER_INTERFACE"
}

otb_tracker_init_tracking "$@"
echo "[$OTB_TRACKER_OPTIONS]" > /toto
OTB_TRACKER_METHOD='dns'
_get_interface_ip
result=$( dig "$OTB_TRACKER_DOMAIN" @"$OTB_TRACKER_HOST" -b "$interface_ip" +time="$OTB_TRACKER_TIMEOUT" +short $OTB_TRACKER_OPTIONS)

otb_tracker_set_status "$?"

[ "$OTB_TRACKER_STATUS" = "OK" ] && OTB_TRACKER_INTERFACE_PUBLIC_IP="$result"

otb_tracker_post_tracking
